services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: odyss
      MONGO_INITDB_ROOT_PASSWORD: odyss1
    networks:
      - odyss.ai

  backend:
    build:
      context: ./Odyss.AI.Backend
    environment:
      - ENVIRONMENT=prod
      - SERVICE_ENDPOINT_SELECTION=teseract
    container_name: backend
    ports:
      - "443:443"
    volumes:
      - shared_data:/shared_data
      - /etc/ssh/id_ed25519:/root/.ssh/id_ed25519:ro
      - /etc/ssh/id_ed25519.pub:/root/.ssh/id_ed25519.pub:ro
    depends_on:
      - mongodb
      - qdrant
      - text_embeddings_inference
      - ocr
    networks:
      - odyss.ai
  
  ocr:
    build:
      context: ./Odyss.AI.Backend.OCR
    container_name: ocr
    volumes:
      - shared_data:/shared_data
    ports:
      - "5050:5050"
    networks:
      - odyss.ai

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - odyss.ai


  frontend:
    build:
      context: ./Odyss.AI.Frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - odyss.ai

  llm:
    build:
      context: ./Odyss.AI.Backend.LLM
    container_name: llm
    ports:
      - "5150:5150"
    depends_on:
      - mongodb
      - qdrant
      - text_embeddings_inference
    networks:
      - odyss.ai

  text_embeddings_inference:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
    container_name: text_embeddings_inference
    ports:
      - "8080:8080"
    volumes:
      - tei:/data/tei
    command: --model-id BAAI/bge-large-en-v1.5 --hostname 0.0.0.0 --port 8080 --payload-limit 20000000 --max-batch-tokens 1000000 --max-client-batch-size 16 # 10MB
    environment:
      - PAYLOAD_LIMIT=20000000
      - MAX_BATCH_TOKENS=1000000
      - PORT=8080
    networks:
      - odyss.ai


  
volumes:
  mongo_data:
    driver: local
  qdrant_storage:
    driver: local
  shared_data:
    driver: local
  tei:
    driver: local

networks:
  odyss.ai:
    driver: bridge