name: Deploy with Docker

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory /var/opt/Odyss.AI

      - name: Deploy with Docker
        run: |
          cd /var/opt/Odyss.AI
          sudo git pull origin dev
          sudo docker-compose down
          sudo docker-compose build
          sudo docker-compose up -d